### ISSUE TITLE
Edit Person List View - Unrequired filtering

### ISSUE THREAD

**Issue by jowhee3011** [AY2425S1-CS2103T-T11-3/tp#125]
When edited against an existing contact, person view changes which is not needed.

Should check for existing person, number or address first before changing filteredPersonsList

![image](https://github.com/user-attachments/assets/b51f8e5b-93b0-4f37-830b-6a5965ce4231)

**Comment by VedJoshi** [comment]
Does not seem to change anymore can help check again? @jowhee3011

**Comment by jowhee3011** [comment]
still does the same for me

**Comment by SherniceSng** [comment]
okay i get what you mean. Fixed in my new PR.
