### ISSUE TITLE
Vieww shows persons list sometimes only

### ISSUE THREAD

**Issue by jowhee3011** [AY2425S1-CS2103T-T11-3/tp#127]
This does not show the client contact.
![image](https://github.com/user-attachments/assets/3b8fe14e-0249-491b-85cc-0b296da1cd06)
This shows the client contact.
![image](https://github.com/user-attachments/assets/72666380-a168-44e4-aaa2-41efa9f0ec79)

Is there a way for the GUI to state which contact belongs to the client? So it's easier to differentiate from the other contacts?\.

**Comment by Droas590** [comment]
thats weird cuz mine works well. Can you send me your addressbook.json

**Comment by SherniceSng** [comment]
Works on my side as well.

**Comment by VedJoshi** [comment]
same I just tested it also, works.

**Comment by jowhee3011** [comment]
my addressbook json changed but ill close issue since its okay for yall
