### ISSUE TITLE
date invalid error msg inaccurate

### ISSUE THREAD

**Issue by Droas590** [AY2425S1-CS2103T-T11-3/tp#129]
![image](https://github.com/user-attachments/assets/4de5e104-3899-492e-87e5-98beec6dc811)

**Comment by jowhee3011** [comment]
wait but the inputed date is not in yyyy-MM-dd format, bc the month is wrong

**Comment by Droas590** [comment]
thats fair

**Comment by VedJoshi** [comment]
close liao
