### ISSUE TITLE
Error message for assigning the same role

### ISSUE THREAD

**Issue by SherniceSng** [AY2425S1-CS2103T-T11-3/tp#154]
The error message can be improved

![image](https://github.com/user-attachments/assets/c9323731-bc57-465f-9087-d4ec9e05d1b8)

**Comment by yikjunxian** [comment]
Resolved :)
<img width="729" alt="image" src="https://github.com/user-attachments/assets/0488269f-2681-4cff-9242-d980de4462e2">
