### ISSUE TITLE
vieww does not truncate wedding list for INDEX

### ISSUE THREAD

**Issue by yikjunxian** [AY2425S1-CS2103T-T11-3/tp#157]
still shows all the wedding after vieww command by INDEX
<img width="737" alt="image" src="https://github.com/user-attachments/assets/2f709527-042e-4a8b-b389-31a6962ba26b">
compared to vieww by wedding name
<img width="735" alt="image" src="https://github.com/user-attachments/assets/d61061c4-6d16-47cd-8401-1da80cfe51c6">

minor side note: can label venue in GUI, e.g. Venue: Raffles Hall.

**Comment by Droas590** [comment]
thx shernice
