### ISSUE TITLE
[Vieww] Should we allow ' in vieww NAME

### ISSUE THREAD

**Issue by jowhee3011** [AY2425S1-CS2103T-T11-3/tp#185]
Should we allow this?

![image](https://github.com/user-attachments/assets/0da7aebe-d99e-45aa-bd89-2db8046dbc4e)
![image](https://github.com/user-attachments/assets/b7821898-cf08-4e91-84ff-a4168a264bf8)

**Comment by Droas590** [comment]
just havent pr
