### ISSUE TITLE
[PE-D][Tester A] .jar file in UG leads to AB3 Release, instead of Bridal Boss release

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T11-3/tp#220]
![image.png](https://raw.githubusercontent.com/Shantaa/ped/main/files/7c2213bf-6edd-4ad7-a6f3-eb6b04d911ed.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: Shantaa/ped#1

**Comment by VedJoshi** [comment]
closed - duplicated
