### ISSUE TITLE
[PE-D][Tester C] Wrong app title name

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T11-3/tp#225]
The app title name still states `Address App`, while it should state `Bridal Boss` to match the name of the app developed.

![image.png](https://raw.githubusercontent.com/matthewyip1511/ped/main/files/02f2b529-3e6f-4acc-8531-d10f6e7b8827.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: matthewyip1511/ped#3

**Comment by SherniceSng** [comment]
Done!

**Comment by SherniceSng** [comment]
![image](https://github.com/user-attachments/assets/1aec86f4-aaea-43e5-a34d-509756cf16fe)

Just checked and this is allowed to do!
