### ISSUE TITLE
[PE-D][Tester A] Email domain input error

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T11-3/tp#226]
![image.png](https://raw.githubusercontent.com/Shantaa/ped/main/files/af0e79cc-672b-452d-bc73-b1797b172a5f.png)

I used 'e/johnd@e-a' as the input for the email field (specifically the domain), which I believe meets the criteria of a) having two characters, b) not starting or ending with hypens, and yet I get an error attempting to add this into the addressBook

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: Shantaa/ped#2

**Comment by jowhee3011** [comment]
Add to constraints that last 2 chars cannot be special chars
