### ISSUE TITLE
[PE-D][Tester B] Vertical resizing of app leaves a large white bar 

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T11-3/tp#233]
When fitting the app to full screen, or extending the height of the app, the resizing causes there to be a large white space at the bottom of the UI. Ideally the UI should stretch to fit the entire height of the screen.

![BBSS1.png](https://raw.githubusercontent.com/kushaldas27/ped/main/files/fbf9326c-1d70-4f78-a530-997329398dac.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: kushaldas27/ped#1

**Comment by Droas590** [comment]
same as issue #224
