### ISSUE TITLE
[PE-D][Tester B] Top bar of UI shows incorrect app name

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T11-3/tp#236]
The top bar of the app incorrectly shows the name of the app as “Address App”. Ideally it should be changed to e.g. “Bridal Boss App”

![BBSS2.png](https://raw.githubusercontent.com/kushaldas27/ped/main/files/d53fa91a-78b2-462e-b688-f1c0e2512332.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: kushaldas27/ped#2

**Comment by Droas590** [comment]
same as #225
