### ISSUE TITLE
[PE-D][Tester A] Typo in Viewing a Contact

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T11-3/tp#241]
![image.png](https://raw.githubusercontent.com/Shantaa/ped/main/files/290e0dd4-bd35-4513-a939-0627738e850a.png)

Sorry but I think it should be 'an Own Wedding label'...

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Shantaa/ped#6

**Comment by Droas590** [comment]
can't believe this is catched
