### ISSUE TITLE
[PE-D][Tester E] Unable to delete date of wedding

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T11-3/tp#256]
After adding a date for a wedding, there is no function to remove the date (for eg if the date changes and becomes undecided). Would it better to include a function to allow deletion of date or allow blanks like role assignment to remove it?
![Screenshot 2024-11-08 at 5.13.19 PM.png](https://raw.githubusercontent.com/sarahteonin/ped/main/files/c478ec42-b873-4b23-b8de-700b68806a97.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: sarahteonin/ped#9

**Comment by SherniceSng** [comment]
Add in UG that cannot delete venue and date, only can edit.
