### ISSUE TITLE
[PE-D][Tester B] Phone number constraints are too limiting

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T11-3/tp#278]
Currently the constraints on the phone number field is 8 digits with the starting digit being 8 or 9. This fails to include telephone numbers (starts with 6) and foreign numbers that start with other digits and can be of varying length e.g. +60 123 45 6789 is a valid Malaysian phone number. Given that clients having weddings very possibly can be from international countries with non-Singaporean phone numbers (while still being able to communicate with those numbers using Whatsapp/ Telegram/I nternational Calls), the strict restriction on the phone number field fails to account for these cases

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: kushaldas27/ped#13

**Comment by Droas590** [comment]
can state in UG

**Comment by jowhee3011** [comment]
Or do we wanna include the stated possibilities? They're kinda valid too, and we js need to change REGEX

**Comment by SherniceSng** [comment]
I think we can definitely do the start with '6', but the rest is a bit tough. So probably specify in UG that this is only for Singaporean number. If want, can add in DG that an enhancement is to allow non-Singapore numbers
