### ISSUE TITLE
[PE-D][Tester B] Contacts should be allowed to have non-unique phone numbers and email addresses

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T11-3/tp#279]
Currently there is a restriction that only allows unique phone numbers and email addresses to be added as contacts to the app. There are possible cases however where two individuals may share the same phone number and/or the same email address e.g. business/ organization phone number or email address instead of their personal ones.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: kushaldas27/ped#14

**Comment by Droas590** [comment]
state in UG
